name: tp
favicon: null
layout_spectrum: 0.09943554387427866
typography_spectrum: 0.9360078668687493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6404818648006767
  lightness: 0.6133591225370765
  saturation: 0.060988802928477526
  rhythmicContrast: 0.35113850655034184
purpose: []
